name: booking_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
#--------------------------------Packages--------------------------------#
dependencies:
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.8
  flutter_chat_types: ^3.6.2
  table_calendar: ^3.0.9
  stomp_dart_client: 0.4.4
  web_socket_channel: ^2.4.0
  image_picker: ^1.0.4
  #google
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.4.0

  # Utility Packages
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^1.1.0
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1


  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8


  # State Management
  get: ^4.6.5
  get_storage: ^2.0.3
  shared_preferences: ^2.5.3
  uuid: ^4.5.2
  flutter_secure_storage: ^9.2.4
  
  
  


#--------------------------------Packages Ends --------------------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  flutter_lints: ^5.0.0

flutter:  
  uses-material-design: true

#--------------------------------Local Assets --------------------------------#
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    - assets/fonts/
  
#--------------------------------Fonts --------------------------------#
  fonts:
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlayfairDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/PlayfairDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/PlayfairDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/PlayfairDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/PlayfairDisplay-BlackItalic.ttf
          weight: 900
          style: italic





















